const { createClient } = require("@supabase/supabase-js");

const SUPABASE_URL = process.env.SUPABASE_URL || "https://ecikviwuxfieryrmfgdq.supabase.co";
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY || "sb_publishable_qZmFog48wGY8aMzEzl3P2Q_bFktF5X3";

module.exports = async (req, res) => {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "GET, POST, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type, Authorization");
  if (req.method === "OPTIONS") return res.status(200).end();
  if (req.method !== "POST") return res.status(405).json({ error: "Method not allowed" });

  try {
    const phoneOrAccount = req.body.phone || req.body.account;
    const email = req.body.email;
    const password = req.body.password;
    
    if (!password) return res.status(400).json({ error: "Password required" });

    const sb = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
      auth: { autoRefreshToken: false, persistSession: false }
    });

    var userEmail = null;
    var profile = null;

    // Login by email (if email field is provided)
    if (email) {
      userEmail = email.toLowerCase().trim();
      // Look up by email in users table
      const { data: emailProfile } = await sb
        .from("users")
        .select("*")
        .eq("email", userEmail)
        .single();
      profile = emailProfile;
    }
    // Login by phone
    else if (phoneOrAccount) {
      const { data: phoneProfile, error: profileError } = await sb
        .from("users")
        .select("*")
        .eq("phone", phoneOrAccount)
        .single();

      if (profileError || !phoneProfile) {
        // Try without leading zeros / different format
        var cleanPhone = phoneOrAccount.replace(/[\s\-\(\)]/g, "");
        var altPhone = null;
        if (cleanPhone.startsWith("0") && cleanPhone.length === 11) {
          altPhone = "+234" + cleanPhone.substring(1);
        } else if (cleanPhone.startsWith("234") && cleanPhone.length === 13) {
          altPhone = "0" + cleanPhone.substring(3);
        } else if (cleanPhone.startsWith("+234") && cleanPhone.length === 14) {
          altPhone = "0" + cleanPhone.substring(4);
        }
        if (altPhone) {
          const { data: altProfile } = await sb
            .from("users")
            .select("*")
            .eq("phone", altPhone)
            .single();
          profile = altProfile;
        }
      } else {
        profile = phoneProfile;
      }

      if (!profile || !profile.email) {
        return res.status(401).json({ error: "Invalid phone number or password" });
      }
      userEmail = profile.email.toLowerCase();
    } else {
      return res.status(400).json({ error: "Phone number or email required" });
    }

    if (!userEmail) {
      return res.status(401).json({ error: "No email linked to this account" });
    }

    // Sign in via Supabase Auth
    const { data, error } = await sb.auth.signInWithPassword({
      email: userEmail,
      password
    });

    if (error) {
      return res.status(401).json({ error: "Invalid credentials" });
    }

    if (!data.user) {
      return res.status(401).json({ error: "Login failed" });
    }

    // For @nogin.nova.local emails, auto-confirm is handled by Supabase
    // Allow login regardless of email confirmation status for these auto-generated emails
    var isAutoGenerated = userEmail.indexOf("@nogin.nova.local") > -1;

    if (!data.user.email_confirmed_at && !isAutoGenerated) {
      return res.json({
        success: true,
        token: data.session?.access_token || "",
        user: {
          id: data.user.id,
          email: userEmail,
          name: profile ? profile.name : "",
          phone: profile ? profile.phone : phoneOrAccount,
          needs_email_confirmation: true
        },
        message: "Please check your email to confirm your account, then login again."
      });
    }

    // Get fresh profile data if not already loaded
    if (!profile) {
      const { data: freshProfile } = await sb
        .from("users")
        .select("*")
        .eq("email", userEmail)
        .single();
      profile = freshProfile || { id: data.user.id, email: userEmail };
    }

    // Add phone_masked
    if (profile && profile.phone) {
      var p = String(profile.phone);
      profile.phone_masked = "********" + p.slice(-4);
    }

    return res.json({
      success: true,
      token: data.session?.access_token || "",
      user: profile || { id: data.user.id, email: userEmail }
    });
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
};
